//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceToVisit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlaceToVisit()
        {
            this.TourPlaces = new HashSet<TourPlace>();
        }
    
        public int id { get; set; }
        public string PName { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Photos { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourPlace> TourPlaces { get; set; }
    }
}
