//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport_Tours
    {
        public int id { get; set; }
        public Nullable<int> TourID { get; set; }
        public Nullable<int> VehicleID { get; set; }
    
        public virtual Tour Tour { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
